version: '3.8'

services:
  web:
    build: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    container_name: telegram_bot
    depends_on:
      - mongo
    env_file:
      - .env
